apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ .Release.Name }}-add-secrets
rules:
  - apiGroups:
    - ''
    resources:
    - secrets
    verbs:
    - get
    - create
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-add-secrets-default
roleRef:
  kind: Role
  name: {{ .Release.Name }}-add-secrets
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{.Release.Namespace}}
